package com.Guess.ReportsPlus.util.Misc;

import java.util.Arrays;
import java.util.List;

public class dropdownInfo {
	
	public static final List<String> areaList = customizationDataLoader.areaList;
	public static final List<String> searchMethods = customizationDataLoader.searchMethods;
	public static final List<String> searchTypes = customizationDataLoader.searchTypes;
	public static final List<String> carColors = customizationDataLoader.carColors;
	public static final List<String> vehicleTypes = customizationDataLoader.vehicleTypes;
	
	public static final List<String> divisions = customizationDataLoader.divisions;
	public static final List<String> agencies = customizationDataLoader.agencies;
	public static final List<String> ranks = customizationDataLoader.ranks;
	public static final List<String> streetList = Arrays.asList("N/A", "Abattoir Avenue", "Abe Milton Parkway",
	                                                            "Ace Jones Drive", "Adam's Apple Boulevard",
	                                                            "Aguja Street", "Alta Place", "Alta Street",
	                                                            "Amarillo Vista", "Amarillo Way", "Americano Way",
	                                                            "Atlee Street", "Autopia Parkway",
	                                                            "Banham Canyon Drive", "Barbareno Road",
	                                                            "Bay City Avenue", "Bay City Incline",
	                                                            "Baytree Canyon Road", "Boulevard Del Perro",
	                                                            "Bridge Street", "Brouge Avenue", "Buccaneer Way",
	                                                            "Buen Vino Road", "Caesars Place", "Calais Avenue",
	                                                            "Calafia Road", "Capital Boulevard", "Carcer Way",
	                                                            "Carson Avenue", "Cassidy Trail", "Cat-Claw Avenue",
	                                                            "Chianski Passage", "Cholla Road",
	                                                            "Cholla Springs Avenue", "Chum Street",
	                                                            "Chupacabra Street", "Clinton Avenue",
	                                                            "Cockingend Drive", "Conquistador Street",
	                                                            "Cortes Street", "Cougar Avenue", "Covenant Avenue",
	                                                            "Cox Way", "Crusade Road", "Davis Avenue",
	                                                            "Decker Street", "Del Perro Freeway", "Didion Drive",
	                                                            "Dorset Drive", "Dorset Place", "Dry Dock Street",
	                                                            "Duluoz Avenue", "Dunstable Drive", "Dunstable Lane",
	                                                            "Dutch London Street", "East Galileo Avenue",
	                                                            "East Joshua Road", "East Mirror Drive",
	                                                            "Eastbourne Way", "Eclipse Boulevard", "Edwood Way",
	                                                            "El Burro Boulevard", "El Rancho Boulevard",
	                                                            "Elgin Avenue", "Elysian Fields Freeway",
	                                                            "Equality Way", "Exceptionalists Way",
	                                                            "Fantastic Place", "Fenwell Place",
	                                                            "Fort Zancudo Approach Road", "Forum Drive",
	                                                            "Fudge Lane", "Galileo Road", "Gentry Lane",
	                                                            "Ginger Street", "Glory Way", "Goma Street",
	                                                            "Great Ocean Highway", "Grapeseed Avenue",
	                                                            "Grapeseed Main Street", "Greenwich Parkway",
	                                                            "Greenwich Place", "Greenwich Way", "Grove Street",
	                                                            "Hanger Way", "Hangman Avenue", "Hardy Way",
	                                                            "Hawick Avenue", "Heritage Way", "Hillcrest Avenue",
	                                                            "Hillcrest Ridge Access Road", "Imagination Court",
	                                                            "Industry Passage", "Ineseno Road", "Integrity Way",
	                                                            "Interstate 1", "Interstate 2", "Interstate 4",
	                                                            "Interstate 5", "Invention Court",
	                                                            "Innocence Boulevard", "Jamestown Street", "Joad Lane",
	                                                            "Joshua Road", "Kimble Hill Drive", "Kortz Drive",
	                                                            "Labor Place", "Laguna Place", "Lake Vinewood Drive",
	                                                            "La Puerta Freeway", "Las Lagunas Boulevard",
	                                                            "Lesbos Lane", "Liberty Street", "Lindsay Circus",
	                                                            "Little Bighorn Avenue", "Lolita Avenue",
	                                                            "Los Santos Freeway", "Low Power Street",
	                                                            "Macdonald Street", "Mad Wayne Thunder Drive",
	                                                            "Magellan Avenue", "Marathon Avenue", "Marina Drive",
	                                                            "Marlowe Drive", "Melanoma Street", "Meringue Lane",
	                                                            "Meteor Street", "Milton Road", "Mirror Park Boulevard",
	                                                            "Mirror Place", "Morningwood Boulevard",
	                                                            "Mount Haan Drive", "Mount Haan Road",
	                                                            "Mount Vinewood Drive", "Mountain View Drive",
	                                                            "Movie Star Way", "Mutiny Road", "New Empire Way",
	                                                            "Nikola Avenue", "Nikola Place", "Niland Avenue",
	                                                            "North Archer Avenue", "North Calafia Way",
	                                                            "North Conker Avenue", "North Rockford Drive",
	                                                            "North Sheldon Avenue", "Nowhere Road", "O'Neil Way",
	                                                            "Occupation Avenue", "Olympic Freeway",
	                                                            "Orchardville Avenue", "Paleto Boulevard",
	                                                            "Palomino Avenue", "Palomino Freeway", "Panorama Drive",
	                                                            "Peaceful Street", "Perth Street",
	                                                            "Picture Perfect Drive", "Plaice Place", "Playa Vista",
	                                                            "Popular Street", "Portola Drive", "Power Street",
	                                                            "Procopio Drive", "Procopio Promenade",
	                                                            "Prosperity Street", "Prosperity Street Promenade",
	                                                            "Pyrite Avenue", "Raton Pass", "Red Desert Avenue",
	                                                            "Richman Street", "Rockford Drive", "Route 1",
	                                                            "Route 11", "Route 13", "Route 14", "Route 15",
	                                                            "Route 16", "Route 17", "Route 18", "Route 19",
	                                                            "Route 20", "Route 22", "Route 23", "Route 68",
	                                                            "Route 68 Approach", "Rub Street", "Sam Austin Drive",
	                                                            "San Andreas Avenue", "San Vitus Boulevard",
	                                                            "Sandcastle Way", "Seaview Road", "Senora Freeway",
	                                                            "Senora Road", "Senora Way", "Shank Street",
	                                                            "Signal Street", "Sinner Street", "Sinners Passage",
	                                                            "Smoke Tree Road", "South Arsenal Street",
	                                                            "South Boulevard Del Perro", "South Mo Milton Drive",
	                                                            "South Rockford Drive", "South Shambles Street",
	                                                            "Spanish Avenue", "Steele Way", "Strangeways Drive",
	                                                            "Strawberry Avenue", "Supply Street", "Sustancia Road",
	                                                            "Swiss Street", "Tackle Street", "Tangerine Street",
	                                                            "Tongva Drive", "Tower Way", "Tug Street", "Union Road",
	                                                            "Utopia Gardens", "Vespucci Boulevard",
	                                                            "Vinewood Boulevard", "Vinewood Park Drive",
	                                                            "Vitus Street", "Voodoo Place",
	                                                            "West Eclipse Boulevard", "West Galileo Avenue",
	                                                            "West Mirror Drive", "Whispymound Drive",
	                                                            "Wild Oats Drive", "York Street", "Zancudo Avenue",
	                                                            "Zancudo Barranca", "Zancudo Road", "Zancudo Trail");
}
