package com.drozal.dataterminal.util.Misc;

import java.util.Arrays;
import java.util.List;

public class dropdownInfo {
	public static final List<String> areaList = Arrays.asList("N/A", "Alamo Sea", "Alta", "Backlot City",
	                                                          "Banham Canyon",
	                                                          "Banning", "Baytree Canyon", "Bolingbroke Penitentiary",
	                                                          "Burton", "Cape Catfish", "Cayo Perico",
	                                                          "Chamberlain Hills", "Chiliad Mountain State Wilderness",
	                                                          "Chumash", "Cypress Flats", "Davis", "Davis Quartz",
	                                                          "Del Perro", "Del Perro Beach", "Dignity Village",
	                                                          "Downtown Vinewood", "East Vinewood", "El Burro Heights",
	                                                          "Elysian Island", "Fort Zancudo", "Galilee",
	                                                          "Galileo Park", "Great Chaparral",
	                                                          "GWC and Golfing Society", "Harmony",
	                                                          "Heart Attacks Beach", "La Mesa", "La Puerta",
	                                                          "Lago Zancudo", "Lake Vinewood", "Lake Vinewood Estates",
	                                                          "Legion Square", "Little Seoul",
	                                                          "Los Santos International Airport", "Ludendorff",
	                                                          "Marlowe Vineyards", "Mirror Park",
	                                                          "Mirror Park Railyard", "Mission Row", "Morningwood",
	                                                          "Mount Chiliad", "Mount Gordo", "Mount Josiah",
	                                                          "Murrieta Heights", "North Chumash", "North Point",
	                                                          "Pacific Bluffs", "Paleto Bay", "Paleto Cove",
	                                                          "Palomino Highlands", "Pillbox Hill",
	                                                          "Port of Los Santos", "Procopio Beach", "Puerto Del Sol",
	                                                          "Rancho", "Redwood Lights Track", "Richman (HD Universe)",
	                                                          "Richman Glen", "Rockford Hills", "Sandy Shores",
	                                                          "Stab City", "Strawberry", "Tataviam Mountains",
	                                                          "Terminal", "Textile City", "Tongva Hills",
	                                                          "Tongva Valley", "Vespucci Beach", "Vespucci Canals",
	                                                          "Vinewood Hills", "Vinewood Racetrack", "West Vinewood");
	public static final List<String> searchMethods = Arrays.asList("N/A", "Search Warrant", "Probable Cause",
	                                                               "Consent Search", "Exigent Circumstances",
	                                                               "Plain View Doctrine", "Incident to Arrest",
	                                                               "Stop and Frisk", "Terry Frisk", "K-9 Search",
	                                                               "Electronic Surveillance", "Field Sobriety Test");
	public static final List<String> searchTypes = Arrays.asList("N/A", "Vehicle Search", "Personal Search",
	                                                             "Premises Search", "Pat-down Search", "Baggage Search",
	                                                             "Strip Search", "Digital Search", "Consent Search",
	                                                             "Inventory Search");
	public static final List<String> carColors = Arrays.asList("N/A", "Black", "White", "Silver", "Gray", "Red", "Blue",
	                                                           "Green", "Yellow", "Orange", "Brown", "Purple", "Pink",
	                                                           "Teal", "Magenta", "Turquoise", "Gold", "Bronze", "Cyan",
	                                                           "Lime");
	
	public static final List<String> vehicleTypes = Arrays.asList("N/A", "Car", "Truck", "Motorcycle", "Bus", "Van",
	                                                              "SUV", "Pickup Truck", "Box Truck", "Tractor Trailer",
	                                                              "Flatbed", "Bicycle", "Tractor", "RV", "Taxi",
	                                                              "Ambulance", "Fire Truck", "Police Car", "Limousine",
	                                                              "Train", "Boat", "Airplane", "Helicopter", "Scooter",
	                                                              "Jet Ski", "Golf Cart", "Go-Kart");
	
	public static final List<String> divisions = Arrays.asList("=============== LSPD ===============",
	                                                           "===== OFFICE OF OPERATIONS =====",
	                                                           "=== CENTRAL BUREAU ===", "Central Area Patrol Division",
	                                                           "Northeast Area Patrol Division",
	                                                           "East Area Patrol Division",
	                                                           "Northeast Area Patrol Division", "=== SOUTH BUREAU ===",
	                                                           "Southcentral Patrol Division",
	                                                           "Harbour Patrol Division", "Southeast Patrol Division",
	                                                           "=== WEST BUREAU ===", "West Los Santos Patrol Division",
	                                                           "Pacific Patrol Division",
	                                                           "North Pacific Patrol Division", "=== VALLEY BUREAU ===",
	                                                           "Central West Patrol Division", "West Patrol Division",
	                                                           "North Vinewood Patrol Division",
	                                                           "Valley Patrol Division", "",
	                                                           "===== OFFICE OF SPECIAL OPERATIONS =====",
	                                                           "=== DETECTIVE BUREAU ===",
	                                                           "Investigative Analysis Division",
	                                                           "Forensic Science Division",
	                                                           "Technical Investigation Division",
	                                                           "Robbery Homicide Division",
	                                                           "Commercial Crimes Division", "VICE Division",
	                                                           "Juvenile Division", "Gang and Narcotics Division",
	                                                           "=== SPECIAL OPS BUREAU ===", "Major Crimes Division",
	                                                           "Emergency Services Division", "Air Support Division",
	                                                           "Emergency Operations Division",
	                                                           "Marine Enforcement Division",
	                                                           "Los Santos International Police",
	                                                           "Los Santos Port Authority",
	                                                           "===== METROPOLITAN DIVISION =====",
	                                                           "A Platoon (Crime Suppression)",
	                                                           "B Platoon (Crime Suppression)",
	                                                           "C Platoon (Crime Suppression)", "D Platoon (SWAT)",
	                                                           "E Platoon (Mounted Unit)",
	                                                           "G Platoon (Crime Suppression)",
	                                                           "H Platoon (Protection Detail)",
	                                                           "K Platoon (Canine Unit)",
	                                                           "M Platoon (Administration Unit)", "",
	                                                           "=============== LSSD & BCSO ===============",
	                                                           "PATROL OPERATIONS", "NORTH PATROL DIVISION",
	                                                           "SOUTH PATROL DIVISION", "EAST PATROL DIVISION",
	                                                           "CENTRAL PATROL DIVISION", "DETECTIVE DIVISION",
	                                                           "Homicide Bureau", "Commercial Crimes Bureau",
	                                                           "Major Crimes Bureau", "Narcotics Bureau",
	                                                           "Special Victims Bureau",
	                                                           "Autotheft Prevention Taskforce", "",
	                                                           "===== TECHNICAL SERVICES DIVISION =====",
	                                                           "Communications & Fleet Management",
	                                                           "Crime Analysis Program", "Data Systems Bureau",
	                                                           "Records & Identification Bureau",
	                                                           "Scientific Services Bureau", "",
	                                                           "===== CUSTODY OPERATIONS =====",
	                                                           "=== CUSTODY DIVISION ===",
	                                                           "Bolingbroke State Penitentiary",
	                                                           "Education & Rehabilitation", "Food Services Unit",
	                                                           "Inmate Services Bureau", "Inmate Reception Centre",
	                                                           "Medical Services Bureau", "Custody Transport Bureau",
	                                                           "", "===== COUNTYWIDE SERVICES =====",
	                                                           "=== COUNTYWIDE SERVICES DIVISION =",
	                                                           "Community Colleges Bureau",
	                                                           "Citizens on Patrol Program",
	                                                           "Community Policing Program", "County Services Bureau",
	                                                           "Parks Bureau", "Parking Enforcement Bureau",
	                                                           "Reserve Forces Bureau",
	                                                           "=== COURT SERVICES DIVISION ===",
	                                                           "Civil Management Bureau", "Court Services Bureau",
	                                                           "Court Transportation Bureau",
	                                                           "=== HOMELAND SECURITY DIVISION ===",
	                                                           "Air Support Division", "Special Enforcement Detail",
	                                                           "Emergency Operations Bureau", "Transit Services Bureau",
	                                                           "LS Metro Train Bureau", "",
	                                                           "=============== SAHP ===============",
	                                                           "===== FIELD OPERATIONS =====", "Northern Division",
	                                                           "Paleto Division", "City Division", "Sandy Division",
	                                                           "Coastal Division", "Border Division", "Ports Division",
	                                                           "===== PROTECTIVE SERVICES =====",
	                                                           "Air Operations Division", "State Security Division",
	                                                           "Special Weapons And Tactics Division",
	                                                           "===== ADMINISTRATIVE SERVICES =====",
	                                                           "Professional Standards and Ethics Division",
	                                                           "Community Outreach and Media Division",
	                                                           "Employee Safety and Assistance Division",
	                                                           "Enforcement and Planning Division",
	                                                           "Information Management Division",
	                                                           "Special Counsel to Commissioner");
	public static final List<String> agencies = Arrays.asList("Los Santos Police Department",
	                                                          "Los Santos Sheriff's Office",
	                                                          "Blaine County Sheriff's Office",
	                                                          "San Andreas Highway Patrol",
	                                                          "Federal Investigation Bureau",
	                                                          "International Affairs Agency",
	                                                          "San Andreas Parks and Recreation");
	public static final List<String> ranks = Arrays.asList("======= LSPD =======", "Police Officer I",
	                                                       "Police Officer II", "Police Officer III",
	                                                       "Police Officer III+1", "", "Police Detective I",
	                                                       "Police Detective II", "Police Detective III", "",
	                                                       "Police Sergeant I", "Police Sergeant II", "",
	                                                       "Police Lieutenant I", "Police Lieutenant II",
	                                                       "Police Captain I", "Police Captain II", "",
	                                                       "Police Commander", "Deputy Chief of Police",
	                                                       "Assistant Chief of Police", "Chief of Police", "",
	                                                       "======= LSSD =======", "Deputy Sheriff I",
	                                                       "Deputy Sheriff II", "Deputy Sheriff III",
	                                                       "Master Field Training Officer", "", "LSSD Detective", "",
	                                                       "LSSD Sergeant", "", "LSSD Lieutenant", "LSSD Captain", "",
	                                                       "LSSD Area Commander", "LSSD Division Chief",
	                                                       "LSSD Assistant Sheriff", "LSSD Undersheriff",
	                                                       "Los Santos County Sheriff", "", "======= BCSO =======",
	                                                       "Deputy Sheriff I", "Deputy Sheriff II",
	                                                       "Deputy Sheriff III", "Master Field Training Officer", "",
	                                                       "BCSO Detective", "", "BCSO Sergeant", "", "BCSO Lieutenant",
	                                                       "BCSO Captain", "", "BCSO Area Commander",
	                                                       "BCSO Division Chief", "BCSO Assistant Sheriff",
	                                                       "BCSO Undersheriff", "Blaine County Sheriff", "",
	                                                       "======= SAHP =======", "State Trooper I",
	                                                       "State Trooper II", "State Trooper III", "",
	                                                       "SAHP Detective", "", "SAHP Sergeant", "", "SAHP Lieutenant",
	                                                       "SAHP Captain", "", "SAHP Assistant Chief", "SAHP Chief",
	                                                       "SAHP Assistant Commissioner", "SAHP Deputy Commissioner",
	                                                       "SAHP Commissioner");
}
